from turtle import *
from random import randint
def shape(leng,sh):
    for i in range(sh):
        forward(leng)
        right(360/sh)
def moon(a):
    lt(90)
    penup()
    forward(a* .5+ a * .8)
    rt(90)
    forward(2.5*a)
    pendown()
    color("black","grey")
    begin_fill()
    circle(a/6)
    end_fill()
    penup()
    forward(a)
    pendown()
def trees(a):
    forward(2 * a)
    right(90)
    tree(a * .8)
    lt(90)
    forward(a * .5)
    rt(90)
    tree(a * .35)
    rt(90)
    forward(a * .5 + a * .8)
    lt(90)
    tree(a * .5)

def tree(a):
    if(a<15):
        return
    forward(a)
    color("green","yellow")
    begin_fill()
    circle(3)
    end_fill()
    color("brown")
    left(35)
    tree(a*.65)
    right(35)
    tree(a*.65)
    right(35)
    tree(a * .65)
    left(35)
    backward(a)

def star(a):
    x= randint(-a,2*a)
    y= randint( int(1.5*a), int(2.2 * a))
    print(x,y)
    penup()
    goto(x,y)
    pendown()
    pensize((a/100))
    color("white", "grey")
    begin_fill()
    for i in range(6):
        lt(60)
        forward(3)
        rt(120)
        forward(3)
    end_fill()


def hfront(a):
    #color("brown","#9933FF")
    color("brown", "#CCCC00")
    begin_fill()
    shape(a, 4)
    end_fill()
    lt(60)
    color("brown", "red")
    begin_fill()
    shape(a, 3)
    end_fill()

def hside(a):
    forward(a)
    #color("brown", "#FF3399")
    color("brown", "red")
    begin_fill()
    rt(60)
    forward(a)
    rt(60)
    forward(a)
    rt(120)
    forward(a)
    rt(60)
    forward(a)
    end_fill()
    backward(a)
    lt(60)
    backward(a)
    #bottom
    #color("brown", "#9933FF")
    color("brown", "#CCCC00")
    begin_fill()
    lt(90)
    shape(a, 4)
    end_fill()

def hwind(a):
    forward(a)
    rt(90)
    forward(a * .7)
    rt(90)
    penup()
    forward(a * .25)
    pendown()
    r=a*.4
    color("brown", "#808080")
    begin_fill()
    shape(r,4)
    end_fill()
    for i in range(4):
        shape(r*.5,4)
        forward(r)
        rt(90)
    penup()

    backward(a * .25)
    lt(90)
    forward(a*.3)
    pendown()

def hdoor(a):
    r=(a/2)-a*(10/100)
    forward(a*.35)
    color("brown","red")
    begin_fill()
    shape(r,4)
    end_fill()
    forward(r/2)
    rt(90)
    forward(r / 2)
    color("brown","yellow")
    begin_fill()
    circle(2)
    end_fill()
    forward(r / 2)
    lt(180)
    forward(r/2)
    color("brown", "yellow")
    begin_fill()
    circle(2)
    end_fill()
    forward(r/2)
    rt(90)
    #trees(a)


def house(a):
    color("brown")
    hfront(a)
    hside(a)
    hwind(a)
    hdoor(a)

def diagram(a):
    t=Turtle()
    t.screen.bgcolor("black")
    penup()
    forward(a*.8)
    pendown()
    pensize((a / 100) + 1)
    house(a)
    color("brown")
    trees(a)
    moon(a)
    for i in range(8):
        star(a)
    penup()
    goto(0,3*a)
    pendown()

a=int(input())
speed(5000)
diagram(a)
done()